apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-festplatten-anspruch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
